#!/usr/bin/env python3
"""Assemble assets/icons.svg from the Lucide icon set.

The sprite used to be hand-drawn. Lucide (https://lucide.dev, ISC) is a curated
2,000-icon set on the same 24x24 round-cap geometry, so it drops in without any
HTML change: the symbol ids here are the ids the pages already reference.

Two deliberate departures from stock Lucide:

  * **Stroke 1.6, not 2.** Lucide draws at 2. Against Poppins Light headings and
    a sage-on-cream palette that reads heavy, so every symbol is re-weighted.
    The geometry is untouched.
  * **instagram stays hand-drawn.** Lucide dropped brand marks over trademark
    concerns and has no replacement, so the existing glyph is preserved verbatim
    rather than substituted for something that isn't the Instagram mark.

    python3 scripts/build-icons.py --src /path/to/lucide-static

Get the source with:

    curl -sL https://registry.npmjs.org/lucide-static/-/lucide-static-1.34.0.tgz \
      | tar xz -C /tmp/lucide --strip-components=1
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPRITE = ROOT / "assets" / "icons.svg"

# sprite id -> lucide icon name. The comment is why this glyph, where the
# mapping is not the obvious one-to-one.
ICONS = {
    # nature and the farm
    "leaf": "leaf",
    "sprout": "sprout",
    "trees": "trees",
    "wheat": "wheat",
    "flower": "flower",
    "lotus": "flower-2",          # yoga / wellness — the fuller bloom reads as a lotus
    "herb": "leafy-green",
    "veg": "carrot",
    "recycle": "recycle",
    # place and property
    "home": "house",
    "office": "building",
    "city": "building-2",
    "resort": "hotel",
    "pavilion": "tent-tree",      # an open shelter among trees
    "pin": "map-pin",
    "globe": "globe",
    "land": "land-plot",          # a surveyed plot — the investment page's subject
    "route": "route",             # the Regional Ring Road
    # ownership and returns
    "deed": "scroll-text",        # a title document, not a generic file
    "key": "key-round",
    "verified": "badge-check",    # developer track record
    "bundle": "layers",           # land + construction + rental in one
    "growth": "trending-up",
    "percent": "percent",
    "ticket": "ticket",
    "gift": "gift",
    # amenities
    "pool": "waves",
    "dumbbell": "dumbbell",
    "dining": "chef-hat",         # the farm-to-table restaurant
    "banquet": "utensils-crossed",  # a laid place setting, for the celebration hall
    # contact
    "phone": "phone",
    "mail": "mail",
}

# Lucide has no brand marks. Keep whatever the sprite already carries for these.
KEEP_EXISTING = ["instagram"]

HEAD = """<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
  <!-- Icons from Lucide (https://lucide.dev) — ISC licence, see assets/icons.LICENSE.
       Generated by scripts/build-icons.py; edit the mapping there, not this file.
       24x24, stroke 1.6, round caps. Colour inherits via currentColor. -->
"""


def inner(svg_text: str) -> str:
    """The drawable elements of a Lucide file, as one line."""
    body = re.sub(r"^.*?<svg\b[^>]*>", "", svg_text, flags=re.S)
    body = re.sub(r"</svg>\s*$", "", body, flags=re.S)
    body = re.sub(r"\s*\n\s*", "", body.strip())
    return re.sub(r"\s+/>", "/>", body)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default="/tmp/lucide", help="unpacked lucide-static")
    a = ap.parse_args()

    src = pathlib.Path(a.src) / "icons"
    if not src.is_dir():
        print(f"lucide icons not found at {src} — see this file's docstring",
              file=sys.stderr)
        return 1

    missing = [n for n in ICONS.values() if not (src / f"{n}.svg").is_file()]
    if missing:
        print(f"not in this lucide version: {', '.join(sorted(missing))}", file=sys.stderr)
        return 1

    # preserve the hand-drawn symbols Lucide cannot supply
    kept = {}
    if SPRITE.is_file():
        existing = SPRITE.read_text()
        for name in KEEP_EXISTING:
            m = re.search(rf'(<symbol id="{name}".*?</symbol>)', existing, flags=re.S)
            if m:
                kept[name] = m.group(1)
            else:
                print(f"  warning: no existing '{name}' symbol to keep", file=sys.stderr)

    out = [HEAD]
    for sid, icon in ICONS.items():
        body = inner((src / f"{icon}.svg").read_text())
        out.append(
            f'  <symbol id="{sid}" viewBox="0 0 24 24">'
            f'<g fill="none" stroke="currentColor" stroke-width="1.6" '
            f'stroke-linecap="round" stroke-linejoin="round">{body}</g></symbol>\n'
        )
    for name, sym in kept.items():
        out.append(f"  {sym}\n")
    out.append("</svg>\n")

    SPRITE.write_text("".join(out))
    print(f"{len(ICONS)} icons from Lucide + {len(kept)} kept -> "
          f"{SPRITE.relative_to(ROOT)} ({SPRITE.stat().st_size // 1024} KB)")

    lic = pathlib.Path(a.src) / "LICENSE"
    if lic.is_file():
        dest = ROOT / "assets" / "icons.LICENSE"
        dest.write_text(lic.read_text())
        print(f"  licence -> {dest.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
